#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 23 11:22:30 2017


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


@author: alex
"""

fib_list = [1]
even_list = []
i = 1

while (i < 4000000):
    fib_list.append(i)
    i = i + fib_list[-2]
    if i%2==0:
        even_list.append(i)
    
print(fib_list, even_list)
print(sum(even_list))